//! Which Trezor answered. mebit supports exactly one model, the Safe 7, and
//! checks it twice on every connection; nothing is cached across connections.
//!
//! 1. **Before the handshake**: `ThpDeviceProperties.internal_model` arrives
//!    in the channel-allocation response, before any pairing prompt or PIN.
//!    The same bytes are the Noise prologue, so the handshake that follows
//!    only succeeds if they were what the device sent.
//! 2. **After pairing**: `Features` from `GetFeatures`, the device's full
//!    self-description, checked field by field.
//!
//! What a Safe 7 reports, from trezor-firmware `c33f81554a51`:
//! `core/embed/models/T3W1/model_T3W1.h` (`MODEL_NAME "Safe 7"`,
//! `MODEL_INTERNAL_NAME "T3W1"`), `core/src/apps/base.py::get_features`
//! (`vendor="trezor.io"`), and trezorlib's model registry, which names T3W1's
//! minimum firmware 2.9.3 and detects models by `internal_model` first.
//!
//! A name or advertisement is never proof of the model: other models answer
//! over BLE too (the firmware tree has a second BLE-capable model, `T3T2`).

use super::protos::management::Features;
use super::protos::management::features::Capability;
use super::protos::thp::{ThpDeviceProperties, ThpPairingMethod};
use super::{TrezorError, decode};

pub const SAFE7_INTERNAL_MODEL: &str = "T3W1";
pub const SAFE7_MODEL: &str = "Safe 7";
pub const TREZOR_VENDOR: &str = "trezor.io";
/// trezorlib `_modeldata/T3W1.py`: `minimum_version=(2, 9, 3)`.
pub const MIN_FIRMWARE: (u32, u32, u32) = (2, 9, 3);
/// THP's major version; `trezor-thp` speaks 2.x.
const THP_MAJOR: u32 = 2;

/// A connected Trezor that passed both checks.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Safe7Identity {
    /// Always `"Safe 7"`.
    pub model: String,
    /// Always `"T3W1"`.
    pub internal_model: String,
    /// Major, minor, patch.
    pub firmware: (u32, u32, u32),
    /// Random per device, regenerated by a wipe.
    pub device_id: Option<String>,
    /// The name the user gave the device.
    pub label: Option<String>,
}

impl Safe7Identity {
    pub fn firmware_version(&self) -> String {
        let (major, minor, patch) = self.firmware;
        format!("{major}.{minor}.{patch}")
    }
}

/// What gate 1 accepted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct DeviceProperties {
    pub(super) protocol: (u8, u8),
    pub(super) code_entry: bool,
}

/// Gate 1: refuses anything but a Safe 7 before the handshake starts.
pub(super) fn check_device_properties(bytes: &[u8]) -> Result<DeviceProperties, TrezorError> {
    let properties: ThpDeviceProperties = decode(bytes)?;
    let internal_model = properties.internal_model.unwrap_or_default();
    if internal_model != SAFE7_INTERNAL_MODEL {
        return Err(TrezorError::UnsupportedModel(format!(
            "internal model {internal_model:?}"
        )));
    }
    let (Some(major), Some(minor)) = (
        properties.protocol_version_major,
        properties.protocol_version_minor,
    ) else {
        return Err(TrezorError::Protocol(
            "the device properties carry no protocol version".into(),
        ));
    };
    if major != THP_MAJOR {
        return Err(TrezorError::UnsupportedFirmware(format!(
            "Trezor-Host Protocol {major}.{minor}"
        )));
    }
    let code_entry = properties
        .pairing_methods
        .iter()
        .any(|method| method.enum_value() == Ok(ThpPairingMethod::CodeEntry));
    Ok(DeviceProperties {
        protocol: (THP_MAJOR as u8, u8::try_from(minor).unwrap_or(u8::MAX)),
        code_entry,
    })
}

/// Gate 2: checks the device's `Features`. The model checks come first, so a
/// different model is reported as such and not as, say, old firmware.
pub(super) fn check_features(features: &Features) -> Result<Safe7Identity, TrezorError> {
    let vendor = features.vendor.as_deref().unwrap_or_default();
    if vendor != TREZOR_VENDOR {
        return Err(TrezorError::UnsupportedModel(format!("vendor {vendor:?}")));
    }
    if features.bootloader_mode == Some(true) {
        return Err(TrezorError::Bootloader);
    }
    let internal_model = features.internal_model.as_deref().unwrap_or_default();
    let model = features.model.as_deref().unwrap_or_default();
    if internal_model != SAFE7_INTERNAL_MODEL || model != SAFE7_MODEL {
        return Err(TrezorError::UnsupportedModel(format!(
            "internal model {internal_model:?}, model {model:?}"
        )));
    }

    let (Some(major), Some(minor), Some(patch)) = (
        features.major_version,
        features.minor_version,
        features.patch_version,
    ) else {
        return Err(TrezorError::Protocol(
            "Features carry no firmware version".into(),
        ));
    };
    let firmware = (major, minor, patch);
    if firmware < MIN_FIRMWARE {
        let (min_major, min_minor, min_patch) = MIN_FIRMWARE;
        return Err(TrezorError::UnsupportedFirmware(format!(
            "{major}.{minor}.{patch}, older than {min_major}.{min_minor}.{min_patch}"
        )));
    }
    let bitcoin = features
        .capabilities
        .iter()
        .any(|capability| capability.enum_value() == Ok(Capability::Capability_Bitcoin));
    if !bitcoin {
        return Err(TrezorError::UnsupportedFirmware(
            "the firmware has no Bitcoin support".into(),
        ));
    }
    if features.initialized != Some(true) {
        return Err(TrezorError::NotInitialised);
    }

    Ok(Safe7Identity {
        model: model.to_owned(),
        internal_model: internal_model.to_owned(),
        firmware,
        device_id: features.device_id.clone(),
        label: features.label.clone(),
    })
}

#[cfg(test)]
pub(super) mod tests {
    use protobuf::{EnumOrUnknown, Message};

    use super::*;

    pub(in super::super) fn safe7_properties() -> Vec<u8> {
        properties("T3W1", 2, 0, &[ThpPairingMethod::CodeEntry])
    }

    pub(in super::super) fn properties(
        internal_model: &str,
        major: u32,
        minor: u32,
        methods: &[ThpPairingMethod],
    ) -> Vec<u8> {
        let mut properties = ThpDeviceProperties::new();
        properties.internal_model = Some(internal_model.into());
        properties.model_variant = Some(0);
        properties.protocol_version_major = Some(major);
        properties.protocol_version_minor = Some(minor);
        properties.pairing_methods = methods.iter().map(|m| EnumOrUnknown::new(*m)).collect();
        properties.write_to_bytes().unwrap()
    }

    /// What a Safe 7 on the minimum firmware reports, per `get_features()`.
    pub(in super::super) fn safe7_features() -> Features {
        let mut features = Features::new();
        features.vendor = Some("trezor.io".into());
        features.model = Some("Safe 7".into());
        features.internal_model = Some("T3W1".into());
        features.major_version = Some(2);
        features.minor_version = Some(9);
        features.patch_version = Some(3);
        features.initialized = Some(true);
        features.device_id = Some("D3V1CE".into());
        features.label = Some("My Trezor".into());
        features.capabilities = [Capability::Capability_Bitcoin, Capability::Capability_BLE]
            .into_iter()
            .map(EnumOrUnknown::new)
            .collect();
        features
    }

    #[test]
    fn accepts_exactly_the_safe7() {
        let gate1 = check_device_properties(&safe7_properties()).unwrap();
        assert_eq!(
            gate1,
            DeviceProperties {
                protocol: (2, 0),
                code_entry: true
            }
        );

        let identity = check_features(&safe7_features()).unwrap();
        assert_eq!(identity.model, "Safe 7");
        assert_eq!(identity.internal_model, "T3W1");
        assert_eq!(identity.firmware_version(), "2.9.3");
        assert_eq!(identity.device_id.as_deref(), Some("D3V1CE"));
    }

    /// Every model in trezor-firmware's `core/embed/models/` plus Trezor One,
    /// with the `MODEL_NAME` it reports. Only T3W1 / "Safe 7" may pass.
    const OTHER_MODELS: [(&str, &str); 9] = [
        ("T1B1", "1"),
        ("T2T1", "T"),
        ("T2B1", "Safe 3"),
        ("T3B1", "Safe 3"),
        ("T3T1", "Safe 5"),
        ("T3T2", "T3T2"),
        ("D001", "D001"),
        ("D002", "D002"),
        ("D003", "D003"),
    ];

    #[test]
    fn gate1_refuses_every_other_model() {
        for (internal_model, _) in OTHER_MODELS {
            let bytes = properties(internal_model, 2, 0, &[ThpPairingMethod::CodeEntry]);
            assert!(
                matches!(
                    check_device_properties(&bytes),
                    Err(TrezorError::UnsupportedModel(_))
                ),
                "{internal_model}"
            );
        }
        for internal_model in ["", "t3w1", "T3W1 ", "T3W"] {
            let bytes = properties(internal_model, 2, 0, &[ThpPairingMethod::CodeEntry]);
            assert!(matches!(
                check_device_properties(&bytes),
                Err(TrezorError::UnsupportedModel(_))
            ));
        }
        // No internal model at all, hand-encoded because the field is
        // proto2-required: protocol_version_major = 2, _minor = 0.
        let bytes = [0x18, 0x02, 0x20, 0x00];
        assert!(matches!(
            check_device_properties(&bytes),
            Err(TrezorError::UnsupportedModel(_))
        ));
    }

    #[test]
    fn gate1_checks_the_protocol_and_records_code_entry() {
        let thp_v3 = properties("T3W1", 3, 0, &[ThpPairingMethod::CodeEntry]);
        assert!(matches!(
            check_device_properties(&thp_v3),
            Err(TrezorError::UnsupportedFirmware(_))
        ));
        let v21 = properties("T3W1", 2, 1, &[ThpPairingMethod::CodeEntry]);
        assert_eq!(check_device_properties(&v21).unwrap().protocol, (2, 1));
        let qr_only = properties("T3W1", 2, 0, &[ThpPairingMethod::QrCode]);
        assert!(!check_device_properties(&qr_only).unwrap().code_entry);
        assert!(matches!(
            check_device_properties(b"\xff\xff not protobuf"),
            Err(TrezorError::Protocol(_))
        ));
    }

    #[test]
    fn gate2_refuses_every_other_model() {
        for (internal_model, model) in OTHER_MODELS {
            let mut features = safe7_features();
            features.internal_model = Some(internal_model.into());
            features.model = Some(model.into());
            assert!(
                matches!(
                    check_features(&features),
                    Err(TrezorError::UnsupportedModel(_))
                ),
                "{internal_model}"
            );
        }
    }

    #[test]
    fn gate2_refuses_mismatched_or_missing_identity() {
        type Mutation = fn(&mut Features);
        let cases: [(&str, Mutation); 7] = [
            ("internal model of a Safe 5", |f| {
                f.internal_model = Some("T3T1".into())
            }),
            ("name of a Safe 5", |f| f.model = Some("Safe 5".into())),
            ("no internal model", |f| f.internal_model = None),
            ("no model", |f| f.model = None),
            ("another vendor", |f| f.vendor = Some("example.com".into())),
            ("no vendor", |f| f.vendor = None),
            ("legacy vendor", |f| {
                f.vendor = Some("bitcointrezor.com".into())
            }),
        ];
        for (case, mutate) in cases {
            let mut features = safe7_features();
            mutate(&mut features);
            assert!(
                matches!(
                    check_features(&features),
                    Err(TrezorError::UnsupportedModel(_))
                ),
                "{case}"
            );
        }
    }

    #[test]
    fn gate2_refuses_bootloader_old_firmware_and_empty_devices() {
        let mut features = safe7_features();
        features.bootloader_mode = Some(true);
        assert!(matches!(
            check_features(&features),
            Err(TrezorError::Bootloader)
        ));

        for version in [(2, 9, 2), (2, 8, 99), (1, 99, 99)] {
            let mut features = safe7_features();
            (
                features.major_version,
                features.minor_version,
                features.patch_version,
            ) = (Some(version.0), Some(version.1), Some(version.2));
            assert!(
                matches!(
                    check_features(&features),
                    Err(TrezorError::UnsupportedFirmware(_))
                ),
                "{version:?}"
            );
        }
        let mut newer = safe7_features();
        (
            newer.major_version,
            newer.minor_version,
            newer.patch_version,
        ) = (Some(2), Some(10), Some(0));
        assert!(check_features(&newer).is_ok());

        let mut no_version = safe7_features();
        no_version.patch_version = None;
        assert!(matches!(
            check_features(&no_version),
            Err(TrezorError::Protocol(_))
        ));

        let mut no_bitcoin = safe7_features();
        no_bitcoin.capabilities = vec![EnumOrUnknown::new(Capability::Capability_BLE)];
        assert!(matches!(
            check_features(&no_bitcoin),
            Err(TrezorError::UnsupportedFirmware(_))
        ));

        for initialized in [None, Some(false)] {
            let mut empty = safe7_features();
            empty.initialized = initialized;
            assert!(matches!(
                check_features(&empty),
                Err(TrezorError::NotInitialised)
            ));
        }
    }
}
